//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Application.Properties.ApplicationResources", typeof(ApplicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot start with underscore.
        /// </summary>
        public static string Good_NameCannotStartWithUnderscore {
            get {
                return ResourceManager.GetString("Good_NameCannotStartWithUnderscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete system defined goods.
        /// </summary>
        public static string Good_UnableToDeleteSystemDefined {
            get {
                return ResourceManager.GetString("Good_UnableToDeleteSystemDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find good.
        /// </summary>
        public static string Good_UnableToFind {
            get {
                return ResourceManager.GetString("Good_UnableToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update system defined goods.
        /// </summary>
        public static string Good_UnableToUpdateSystemDefined {
            get {
                return ResourceManager.GetString("Good_UnableToUpdateSystemDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered order status can not be changed.
        /// </summary>
        public static string Order_DeliveredOrderStatusCanNotBeChanged {
            get {
                return ResourceManager.GetString("Order_DeliveredOrderStatusCanNotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packed or delivered order can not be updated.
        /// </summary>
        public static string Order_PackedOrDeliverdOrderCanNotbeUpdated {
            get {
                return ResourceManager.GetString("Order_PackedOrDeliverdOrderCanNotbeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find order.
        /// </summary>
        public static string Order_UnableToFind {
            get {
                return ResourceManager.GetString("Order_UnableToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find {0}.
        /// </summary>
        public static string Order_UnableToFindGood {
            get {
                return ResourceManager.GetString("Order_UnableToFindGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        public static string Order_UserDoesNotExist {
            get {
                return ResourceManager.GetString("Order_UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password does not match.
        /// </summary>
        public static string User_PasswordAndConfirmPasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("User_PasswordAndConfirmPasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete system defined users.
        /// </summary>
        public static string User_UnableToDeleteSystemDefined {
            get {
                return ResourceManager.GetString("User_UnableToDeleteSystemDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find user.
        /// </summary>
        public static string User_UnableToFind {
            get {
                return ResourceManager.GetString("User_UnableToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update system defined users.
        /// </summary>
        public static string User_UnableToUpdateSystemDefined {
            get {
                return ResourceManager.GetString("User_UnableToUpdateSystemDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot start with underscore.
        /// </summary>
        public static string User_UsernameCannotStartWithUnderscore {
            get {
                return ResourceManager.GetString("User_UsernameCannotStartWithUnderscore", resourceCulture);
            }
        }
    }
}
